version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: gotasker-api
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    ports:
      - 8070:8070

  swagger:
    image: swaggerapi/swagger-ui
    container_name: gotasker-swagger
    volumes:
      - ./doc/openapi:/config
    environment:
      - SWAGGER_JSON=/config/api.yaml
      - PORT=9527
    restart: always
    ports:
      - 9527:9527

  redis:
    image: redis:alpine
    container_name: gotasker-redis
    restart: always
    volumes:
      - type: tmpfs
        target: /data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 1m30s
      retries: 5